### ISSUE TITLE
Cannot change image name in Vagrantfile, results in error with deprecated Centos8

### ISSUE THREAD

**Issue by sheperdsonbrown** [ginigangadharan/vagrant-iac-usecases#1]
Hello, 

First off, Thank you so much for this resource. 

Currently having trouble changing the machine image in Vagrantfile. 

The reason is because ansible-engine has this issue when installing ansible: 

```
==> ansible-engine: Installing Ansible...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

dnf -y --enablerepo=epel install ansible

Stdout from the command:

CentOS Linux 8 - AppStream                      194  B/s |  38  B     00:00    

Stderr from the command:

Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

I tried using different machine image in Vagrantfile 

$ vim virtualbox-ansible-lab/Vagrantfile

IMAGE_NAME = "centos/7"

but I always see centos/8 being used like so: 

```vagrant up
Bringing machine 'ansible-node-1' up with 'virtualbox' provider...
Bringing machine 'ansible-node-2' up with 'virtualbox' provider...
Bringing machine 'ansible-engine' up with 'virtualbox' provider...
==> ansible-node-1: Importing base box '**centos/8**'...
```
And proof ansible was not installed:

```vagrant ssh ansible-engine
[vagrant@ansible-engine1 ~]$ ansible --version
-bash: ansible: command not foundvagrant ssh ansible-engine
[vagrant@ansible-engine1 ~]$ ansible --version
-bash: ansible: command not found
```

I think the repo url has changed for the deprecated Centos8, as referenced here: https://stackoverflow.com/questions/70926799/centos-through-vm-no-urls-in-mirrorlist

**Comment by ginigangadharan** [comment]
@sheperdsonbrown 
Yes, you are right. CentOS Linux 8 had reached the End Of Life (EOL) on December 31st, 2021.
So, we need to adjust the mirror uls to [vault.centos.org](https://vault.centos.org/) if the vagrantbox is based on old CentOS.

Alternatively, you can try with vagrant box for [CentOS 8 Stream](https://app.vagrantup.com/centos/boxes/stream8) or you may switch to [Fedora](https://app.vagrantup.com/fedora/boxes/35-cloud-base).

I have updates the VM image with Fedora 35 anyway and tested here successfully.

```yaml
#IMAGE_NAME = "centos/8"
IMAGE_NAME = "fedora/35-cloud-base"\
```

Let me know if this is working :)

**Comment by ginigangadharan** [comment]
Glad it worked :)
