### ISSUE TITLE
playbook does not exist on the guest: /vagrant/install-minikube.yaml

### ISSUE THREAD

**Issue by Codehunter-py** [ginigangadharan/vagrant-iac-usecases#2]
I did run `vagrant up` in virtualbox-minikube folder and getting error saying no playbook file exists.

**Comment by Codehunter-py** [comment]
I am using vagrant on Windows 10.

**Comment by Codehunter-py** [comment]
Opened pull request for the issue #3

**Comment by ginigangadharan** [comment]
Accepted!

You may check and close the issue.

Thank you.
